-- PR X17: Help Center / FAQ schema + seed.

create table if not exists help_articles (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  question text not null,
  answer text not null,
  audience text not null check (audience in ('candidate','employer','admin','everyone')),
  section text not null,
  sort_index int not null default 0,
  published boolean not null default true,
  updated_at timestamptz not null default now()
);

create index if not exists help_articles_audience_idx on help_articles(audience, section, sort_index);

alter table help_articles enable row level security;

drop policy if exists help_articles_read on help_articles;
create policy help_articles_read on help_articles for select using (published = true);

drop policy if exists help_articles_write on help_articles;
create policy help_articles_write on help_articles for all
  using (exists (select 1 from user_profiles p where p.id = auth.uid() and p.role = 'admin'));

-- Seed (idempotent)
insert into help_articles (slug, question, answer, audience, section, sort_index) values
-- ===== CANDIDATES: Getting started (6) =====
('candidate-create-account', 'How do I create a candidate account?',
 $body$Visit /register and choose "Job Seeker." Verify your email, and you're in. You can upload a resume and fill in your profile at any time after signup.$body$,
 'candidate', 'Getting Started', 1),

('candidate-upload-resume', 'How do I upload my resume?',
 $body$Go to /profile → Resume section. We accept PDF and DOCX up to 5MB. Your resume is stored privately and only shared with employers when you apply to their jobs.$body$,
 'candidate', 'Getting Started', 2),

('candidate-profile-visible', 'Is my profile visible to recruiters?',
 $body$By default your profile is only visible in Talent Search if you opt in. You can toggle this in Settings. When you apply to a job, that specific employer sees your profile regardless of the global setting.$body$,
 'candidate', 'Getting Started', 3),

('candidate-delete-account', 'How do I delete my account?',
 $body$Go to /settings → "Delete my data." Type DELETE to confirm. Your profile, applications, saved jobs, and notifications are permanently removed. Reviews you wrote are anonymized so company ratings remain accurate.$body$,
 'candidate', 'Getting Started', 4),

('candidate-reset-password', 'I forgot my password. How do I reset it?',
 $body$On the login page, click "Forgot password." We'll send a reset link to your email. The link expires after 1 hour — if it expires, request a new one.$body$,
 'candidate', 'Getting Started', 5),

('candidate-email-preferences', 'How do I stop getting emails?',
 $body$Go to /settings → Notification preferences. Toggle off any category (job alerts, application updates, messages, product updates). Changes take effect immediately.$body$,
 'candidate', 'Getting Started', 6),

-- ===== CANDIDATES: Applying to jobs (8) =====
('candidate-apply-job', 'How do I apply to a job?',
 $body$Click "Apply" on any job detail page. If you're logged in, we'll submit your current resume and application details. If not, we'll prompt you to sign in or create an account first — your application is preserved through signup.$body$,
 'candidate', 'Applying', 1),

('candidate-withdraw-application', 'Can I withdraw an application?',
 $body$Yes. Go to /my-jobs → Applied tab. Click Withdraw next to any application. The employer is notified that you're no longer interested.$body$,
 'candidate', 'Applying', 2),

('candidate-apply-again', 'Can I apply to the same job twice?',
 $body$Only if you've withdrawn your first application and the role is still open. From /my-jobs → Archived, click "Apply again" to resubmit.$body$,
 'candidate', 'Applying', 3),

('candidate-application-status', 'How do I track my application status?',
 $body$/my-jobs → Applied tab shows every application. Click "Status" next to any application to see the full timeline: Applied → Viewed → Screening → Interview → Offer/Rejected.$body$,
 'candidate', 'Applying', 4),

('candidate-employer-viewed', 'Did the employer actually see my application?',
 $body$When an employer views your resume or application, you'll see it reflected in the status timeline. "Viewed" means someone from the hiring team opened your materials — not that a decision is imminent.$body$,
 'candidate', 'Applying', 5),

('candidate-screening-questions', 'What are screening questions?',
 $body$Some jobs include extra questions from the employer (e.g., "Are you authorized to work in the US?"). Answer honestly — they're often used as hard filters. We save your answers so you don't retype them across similar roles.$body$,
 'candidate', 'Applying', 6),

('candidate-match-score', 'How is the match score calculated?',
 $body$The ✨ XX% match pill on logged-in users' job cards is generated by an AI model comparing your profile to the job description. Higher scores mean stronger alignment — not a guarantee of an interview.$body$,
 'candidate', 'Applying', 7),

('candidate-saved-jobs-limit', 'Is there a limit on saved jobs?',
 $body$No. Save as many as you like. They're in /my-jobs → Saved tab. Old saved jobs stay there until the role is closed by the employer.$body$,
 'candidate', 'Applying', 8),

-- ===== CANDIDATES: Profile & resume (6) =====
('candidate-skills-section', 'What should I put in the Skills section?',
 $body$5-15 concrete skills that employers search for in your field. Be specific: "PostgreSQL" beats "databases." Skip soft skills like "team player" — the experience section is where soft skills show through outcomes.$body$,
 'candidate', 'Profile', 1),

('candidate-work-experience', 'How detailed should my work experience be?',
 $body$Each role: 3-5 bullets max. Each bullet: verb + outcome + measurable scale. Example: "Rebuilt payment service, cut p99 latency from 320ms to 85ms." Recruiters scan — specificity wins over length.$body$,
 'candidate', 'Profile', 2),

('candidate-job-preferences', 'What are Job Preferences used for?',
 $body$They power job recommendations and saved search alerts. Set desired titles, locations, salary floor, and remote preferences. Employers see them only if you apply or enable Talent Search.$body$,
 'candidate', 'Profile', 3),

('candidate-demographics-eeo', 'Do I have to fill out the Demographics form?',
 $body$No — it's entirely optional. Employers never see your individual responses. The data is used only in aggregate for EEO reporting purposes required by some employers.$body$,
 'candidate', 'Profile', 4),

('candidate-update-profile', 'How often should I update my profile?',
 $body$Every 3-6 months, or whenever something meaningful changes (new role, new skill, new credential). Completeness score on /profile shows what's missing.$body$,
 'candidate', 'Profile', 5),

('candidate-multiple-resumes', 'Can I upload multiple resumes?',
 $body$Currently we store one primary resume per account. If you need to tailor for different roles, upload the most relevant version when you apply. Multi-resume support is on our roadmap.$body$,
 'candidate', 'Profile', 6),

-- ===== EMPLOYERS: Getting started (5) =====
('employer-create-account', 'How do I create an employer account?',
 $body$Visit /register and choose "Employer." After signup, you'll be prompted to create or claim your company profile. Most accounts are approved within 24 hours.$body$,
 'employer', 'Getting Started', 1),

('employer-claim-company', 'I see my company but someone else created the profile. Can I claim it?',
 $body$Yes. Go to your company's profile page and click "Claim this company." Our team verifies the claim (typically within 2 business days) using your company email domain.$body$,
 'employer', 'Getting Started', 2),

('employer-post-job', 'How do I post a job?',
 $body$From /company-dashboard → Jobs tab, click "New Job." Fill in the form or paste a JD and let our AI structure it. Jobs go live immediately and are indexed within an hour.$body$,
 'employer', 'Getting Started', 3),

('employer-xml-feed', 'Can I connect an XML feed?',
 $body$Yes. Admin-managed: contact support with your feed URL. We support JobDiva, Bullhorn, Greenhouse, and most standard XML formats. Jobs sync every 6 hours.$body$,
 'employer', 'Getting Started', 4),

('employer-pricing', 'How much does it cost to post jobs?',
 $body$See /pricing for current tiers. First 5 active job postings are free. Paid plans unlock unlimited postings, featured placement, ATS integrations, and Talent Search.$body$,
 'employer', 'Getting Started', 5),

-- ===== EMPLOYERS: Applicants (5) =====
('employer-view-applicants', 'Where do I see applicants?',
 $body$/company-dashboard → Applicants tab. Toggle between List view and Pipeline (Kanban) view. Drag cards between stages to update status.$body$,
 'employer', 'Applicants', 1),

('employer-ai-screening', 'What does AI Screening do?',
 $body$In the applicant detail modal, click "Run AI Screening." Our model analyzes the candidate's resume against the job and returns a fit score, strengths, and concerns. Meant as a triage aid, not a final decision.$body$,
 'employer', 'Applicants', 2),

('employer-crm-notes', 'How do I add private notes about a candidate?',
 $body$In the applicant detail modal, scroll to "Private notes." Visible to anyone on your company team with employer role. Candidates never see them.$body$,
 'employer', 'Applicants', 3),

('employer-bulk-message', 'Can I message multiple applicants at once?',
 $body$Yes. On the Applicants tab, click "Bulk message." Select recipients, write your message, send. Each person receives it as an in-app direct message.$body$,
 'employer', 'Applicants', 4),

('employer-schedule-interview', 'How do I schedule an interview?',
 $body$Open an applicant's detail modal, click "Schedule interview." Fill in date/time/location/meeting URL. Save to create the record + auto-send details as a message. Click the .ics button to download a calendar invite.$body$,
 'employer', 'Applicants', 5),

-- ===== EMPLOYERS: Reviews & company profile (5) =====
('employer-review-responses', 'Can I respond to reviews?',
 $body$Yes. On /company-dashboard → Reviews tab, find any review and click "Respond." Your response appears publicly under the review. Keep it professional — employer responses are indexed by search engines.$body$,
 'employer', 'Reviews', 1),

('employer-report-review', 'Someone left a fake review. What do I do?',
 $body$Click "Report" on any review. Our moderation team reviews reports within 48 hours. Reviews violating our Content Policy are removed; reviews you simply disagree with stay up.$body$,
 'employer', 'Reviews', 2),

('employer-update-company-profile', 'How do I update my company logo and description?',
 $body$/company-dashboard → Company Profile tab. Upload a logo (square, 512x512 recommended) and edit the description. Changes go live immediately.$body$,
 'employer', 'Reviews', 3),

('employer-why-join-blocks', 'What are Why Join Us blocks?',
 $body$Customizable blocks that appear on your public company profile. Choose from text, quote, stat, image, or video. Use them to showcase benefits, team quotes, growth metrics, or office photos.$body$,
 'employer', 'Reviews', 4),

('employer-team-invites', 'How do I invite teammates?',
 $body$/company-dashboard → Company Profile tab → Team Invites section. Pick a role (Owner, Recruiter, Viewer), generate a link, share it. Links expire after 14 days.$body$,
 'employer', 'Reviews', 5),

-- ===== ACCOUNT & BILLING (4) =====
('billing-change-plan', 'How do I upgrade or downgrade my plan?',
 $body$/company-dashboard → Subscription tab. Stripe Customer Portal handles changes. Upgrades take effect immediately; downgrades at the end of the current billing cycle.$body$,
 'everyone', 'Account & Billing', 1),

('billing-invoice', 'Where do I download invoices?',
 $body$In the Stripe Customer Portal (linked from the Subscription tab). All past invoices are downloadable as PDFs.$body$,
 'everyone', 'Account & Billing', 2),

('billing-refund', 'Do you offer refunds?',
 $body$Monthly plans: no refunds for the current month, but you can cancel to prevent the next renewal. Annual plans: pro-rated refund within the first 30 days. Email support@hirequadrant.com for refund requests.$body$,
 'everyone', 'Account & Billing', 3),

('billing-tax-exempt', 'We're tax-exempt. How do I apply that to my account?',
 $body$Email your resale or tax-exempt certificate to billing@hirequadrant.com. We'll flag your account; future invoices exclude applicable sales tax.$body$,
 'everyone', 'Account & Billing', 4),

-- ===== TRUST & SAFETY (6) =====
('trust-review-rules', 'What rules apply to reviews?',
 $body$Reviews must be based on direct experience. No personal attacks, slurs, PII, defamation, or promotional content. Full policy at /content-policy. Violating reviews are removed and the author may be temporarily or permanently banned.$body$,
 'everyone', 'Trust & Safety', 1),

('trust-anonymous-reviews', 'Can I review anonymously?',
 $body$Your display name is not shown on reviews by default — only the reviewer's role and time-with-company. Your account must still be a real one (no throwaways), so we can enforce rate limits and investigate abuse.$body$,
 'everyone', 'Trust & Safety', 2),

('trust-review-rate-limit', 'Why can't I post a 4th review today?',
 $body$We limit reviews to 3 per user per 24 hours to prevent spam and brigading. The limit resets on a rolling basis.$body$,
 'everyone', 'Trust & Safety', 3),

('trust-two-factor', 'How do I enable two-factor authentication?',
 $body$/settings → Two-factor authentication. Scan the QR in your authenticator app (Google Authenticator, 1Password, Authy), enter the 6-digit code, save the recovery codes somewhere safe.$body$,
 'everyone', 'Trust & Safety', 4),

('trust-sessions', 'How do I see where I'm signed in?',
 $body$/settings → Active sessions. View every active session with device type + last active time. Click "Sign out all others" to end sessions except the current one.$body$,
 'everyone', 'Trust & Safety', 5),

('trust-gdpr-export', 'Can I download all my data?',
 $body$Yes. /settings → Download my data. Generates a JSON archive of your profile, resume, applications, saved jobs, reviews, and notifications. Usually takes under 30 seconds to build.$body$,
 'everyone', 'Trust & Safety', 6),

-- ===== TECHNICAL (5) =====
('technical-why-white-page', 'I'm seeing a white page. What do I do?',
 $body$Hard-refresh (Cmd+Shift+R on Mac, Ctrl+Shift+R on Windows/Linux). If the problem persists in a fresh incognito window, report at /support — include your browser version and the exact URL.$body$,
 'everyone', 'Technical', 1),

('technical-browser-support', 'Which browsers are supported?',
 $body$Latest versions of Chrome, Safari, Firefox, Edge, and Brave. We don't support IE or browsers older than 2 years.$body$,
 'everyone', 'Technical', 2),

('technical-mobile-app', 'Is there a mobile app?',
 $body$Not yet. The site is fully responsive — install it to your home screen for an app-like experience. A native app is on the roadmap.$body$,
 'everyone', 'Technical', 3),

('technical-notifications-not-arriving', 'I'm not getting email notifications. Why?',
 $body$Check /settings → Notification preferences to confirm the category is enabled. Then check your spam folder for mail from notify@hirequadrant.com. Gmail sometimes categorizes as Promotions.$body$,
 'everyone', 'Technical', 4),

('technical-dark-mode', 'How do I enable dark mode?',
 $body$Click the sun/moon icon in the top-right corner of the header. Your preference is saved locally. It also follows your system's light/dark preference by default.$body$,
 'everyone', 'Technical', 5)

on conflict (slug) do nothing;
