-- Backfill geocoding for jobs imported via the XML feed, which never
-- set lat/lng on ingest (only UI-posted jobs did — see NewJobModal.tsx).
-- Generated by a one-time script calling the Mapbox geocoding API for
-- each unique location string among the affected jobs. "Remote" jobs are
-- intentionally left unset — they should never be radius-filtered.
--
-- 6 of the 99 automated results were manually corrected after a sanity
-- check flagged coordinates outside the expected state (Mapbox matched a
-- street name in the wrong state instead of the actual city/town) — see
-- comments below. scripts/migrateJobs.ts is being updated separately so
-- future XML imports geocode on ingest and this doesn't fall behind again.

UPDATE jobs SET lat = 38.934035, lng = -77.177356 WHERE location = 'VA - McLean' AND lat IS NULL;
UPDATE jobs SET lat = 39.097738, lng = -76.84867 WHERE location = 'MD - Laurel' AND lat IS NULL;
UPDATE jobs SET lat = 38.303298, lng = -77.460662 WHERE location = 'VA - Fredericksburg' AND lat IS NULL;
UPDATE jobs SET lat = 39.289643, lng = -76.612299 WHERE location = 'MD - Baltimore' AND lat IS NULL;
UPDATE jobs SET lat = 38.90253, lng = -77.039386 WHERE location = 'DC - Washington' AND lat IS NULL;
UPDATE jobs SET lat = 38.921804, lng = -77.266252 WHERE location = 'VA - Midlothian' AND lat IS NULL;
UPDATE jobs SET lat = 38.751838, lng = -77.471688 WHERE location = 'VA - Manassas' AND lat IS NULL;
UPDATE jobs SET lat = 38.934035, lng = -77.177356 WHERE location = 'VA - Mclean' AND lat IS NULL;
UPDATE jobs SET lat = 38.90253, lng = -77.039386 WHERE location = 'DC - Washington DC' AND lat IS NULL;
UPDATE jobs SET lat = 39.085029, lng = -77.150955 WHERE location = 'MD - Rockville' AND lat IS NULL;
UPDATE jobs SET lat = 42.241808, lng = -70.889994 WHERE location = 'MA - Hingham' AND lat IS NULL;
UPDATE jobs SET lat = 36.850006, lng = -75.976869 WHERE location = 'VA - Virginia Beach' AND lat IS NULL;
UPDATE jobs SET lat = 38.946171, lng = -76.733975 WHERE location = 'MD - Bowie' AND lat IS NULL;
UPDATE jobs SET lat = 36.728194, lng = -76.583215 WHERE location = 'VA - Suffolk' AND lat IS NULL;
UPDATE jobs SET lat = 38.979484, lng = -76.492109 WHERE location = 'MD - Annapolis' AND lat IS NULL;
UPDATE jobs SET lat = 38.88501, lng = -76.91586 WHERE location = 'MD - Capitol Heights' AND lat IS NULL;
UPDATE jobs SET lat = 38.80463, lng = -77.043624 WHERE location = 'VA - Alexandria' AND lat IS NULL;
UPDATE jobs SET lat = 44.546064, lng = -73.15397 WHERE location = 'VT - Colchester' AND lat IS NULL;
UPDATE jobs SET lat = 37.535871, lng = -77.434646 WHERE location = 'VA - Richmond' AND lat IS NULL;
UPDATE jobs SET lat = 32.781339, lng = -96.799759 WHERE location = 'TX - Dallas' AND lat IS NULL;
UPDATE jobs SET lat = 39.192695, lng = -76.724304 WHERE location = 'MD - Hanover' AND lat IS NULL;
UPDATE jobs SET lat = 37.495536, lng = -77.334953 WHERE location = 'VA - Henrico' AND lat IS NULL;
UPDATE jobs SET lat = 38.882264, lng = -77.171148 WHERE location = 'VA - Falls Church' AND lat IS NULL;
UPDATE jobs SET lat = 38.957161, lng = -77.358603 WHERE location = 'VA - Reston' AND lat IS NULL;
UPDATE jobs SET lat = 38.931927, lng = -76.94989 WHERE location = 'MD - Colmar Manor' AND lat IS NULL;
UPDATE jobs SET lat = 35.779557, lng = -78.638148 WHERE location = 'NC - Raleigh' AND lat IS NULL;
UPDATE jobs SET lat = 38.888414, lng = -77.091601 WHERE location = 'VA - Arlington' AND lat IS NULL;
UPDATE jobs SET lat = 38.986254, lng = -77.096712 WHERE location = 'MD - Bethesda' AND lat IS NULL;
UPDATE jobs SET lat = 35.995039, lng = -78.900646 WHERE location = 'NC - Durham' AND lat IS NULL;
UPDATE jobs SET lat = 38.696994, lng = -76.847844 WHERE location = 'MD - Brandywine' AND lat IS NULL;
UPDATE jobs SET lat = 39.952756, lng = -75.166853 WHERE location = 'PA - Philadelphia' AND lat IS NULL;
UPDATE jobs SET lat = 39.043555, lng = -77.487449 WHERE location = 'VA - Ashburn' AND lat IS NULL;
UPDATE jobs SET lat = 39.377074, lng = -76.725257 WHERE location = 'MD - Pikesville' AND lat IS NULL;
UPDATE jobs SET lat = 38.419422, lng = -82.443494 WHERE location = 'WV - Huntington' AND lat IS NULL;
UPDATE jobs SET lat = 38.490662, lng = -76.775026 WHERE location = 'MD - Charlotte Hall' AND lat IS NULL;
UPDATE jobs SET lat = 33.750801, lng = -84.389855 WHERE location = 'GA - Atlanta' AND lat IS NULL;
UPDATE jobs SET lat = 39.172561, lng = -77.203756 WHERE location = 'MD - Montogomery Village' AND lat IS NULL;
UPDATE jobs SET lat = 37.027797, lng = -76.344802 WHERE location = 'VA - Hampton' AND lat IS NULL;
UPDATE jobs SET lat = 37.604084, lng = -77.372066 WHERE location = 'VA - Mechanicsville' AND lat IS NULL;
UPDATE jobs SET lat = 30.15522, lng = -85.660389 WHERE location = 'FL - Panama City' AND lat IS NULL;
UPDATE jobs SET lat = 36.164518, lng = -86.781073 WHERE location = 'TN - Nashville' AND lat IS NULL;
UPDATE jobs SET lat = 41.01957, lng = -92.410665 WHERE location = 'IA - Ottumwa' AND lat IS NULL;
UPDATE jobs SET lat = 38.994578, lng = -77.026954 WHERE location = 'MD - Silver Spring' AND lat IS NULL;
UPDATE jobs SET lat = 39.214717, lng = -76.855986 WHERE location = 'MD - Columbia' AND lat IS NULL;
UPDATE jobs SET lat = 34.729538, lng = -86.585304 WHERE location = 'AL - Huntsville' AND lat IS NULL;
UPDATE jobs SET lat = 39.405649, lng = -76.809511 WHERE location = 'MD - Owings Mills' AND lat IS NULL;
UPDATE jobs SET lat = 38.901569, lng = -77.26521 WHERE location = 'VA - Vienna' AND lat IS NULL;
UPDATE jobs SET lat = 35.227207, lng = -80.84309 WHERE location = 'NC - Charlotte' AND lat IS NULL;
UPDATE jobs SET lat = 30.268072, lng = -97.742806 WHERE location = 'TX - Austin' AND lat IS NULL;
UPDATE jobs SET lat = 39.096836, lng = -76.738113 WHERE location = 'MD - Ft. Meade' AND lat IS NULL;
UPDATE jobs SET lat = 38.514595, lng = -89.981532 WHERE location = 'IL - Belleville' AND lat IS NULL;
UPDATE jobs SET lat = 34.746468, lng = -92.273114 WHERE location = 'AR - Little Rock' AND lat IS NULL;
UPDATE jobs SET lat = 40.259614, lng = -76.881871 WHERE location = 'PA - Harrisburg' AND lat IS NULL;
UPDATE jobs SET lat = 39.001809, lng = -77.403409 WHERE location = 'VA - Sterling' AND lat IS NULL;
UPDATE jobs SET lat = 42.525896, lng = -70.927246 WHERE location = 'MA - Peabody' AND lat IS NULL;
UPDATE jobs SET lat = 38.291211, lng = -76.635635 WHERE location = 'MD - Leonardtown' AND lat IS NULL;
UPDATE jobs SET lat = 33.773561, lng = -84.296521 WHERE location = 'GA - Decatur' AND lat IS NULL;
UPDATE jobs SET lat = 39.179852, lng = -77.265031 WHERE location = 'MD - Germantown' AND lat IS NULL;
UPDATE jobs SET lat = 33.128531, lng = -107.255683 WHERE location = 'NM - Truth or Consequences' AND lat IS NULL;
UPDATE jobs SET lat = 37.222705, lng = -77.287327 WHERE location = 'VA - Prince George' AND lat IS NULL;
UPDATE jobs SET lat = 33.750801, lng = -84.389855 WHERE location = 'GA - ATlanta' AND lat IS NULL;
UPDATE jobs SET lat = 38.658269, lng = -77.249755 WHERE location = 'VA - Woodbridge' AND lat IS NULL;
UPDATE jobs SET lat = 37.293378, lng = -80.054668 WHERE location = 'VA - Salem' AND lat IS NULL;
UPDATE jobs SET lat = 38.896239, lng = -77.428645 WHERE location = 'VA - Chantilly' AND lat IS NULL;
UPDATE jobs SET lat = 39.142189, lng = -77.193362 WHERE location = 'MD - Gaithersburg' AND lat IS NULL;
UPDATE jobs SET lat = 38.367022, lng = -75.599528 WHERE location = 'MD - Salisbury' AND lat IS NULL;
UPDATE jobs SET lat = 39.183711, lng = -78.164159 WHERE location = 'VA - Winchester' AND lat IS NULL;
UPDATE jobs SET lat = 38.830602, lng = -77.189832 WHERE location = 'VA - Annandale' AND lat IS NULL;
UPDATE jobs SET lat = 39.758781, lng = -84.19637 WHERE location = 'OH - Dayton' AND lat IS NULL;
UPDATE jobs SET lat = 38.846266, lng = -77.306605 WHERE location = 'VA - Fairfax' AND lat IS NULL;
UPDATE jobs SET lat = 39.962462, lng = -76.727707 WHERE location = 'PA - York' AND lat IS NULL;
UPDATE jobs SET lat = 35.430834, lng = -82.501312 WHERE location = 'NC - Fletcher' AND lat IS NULL;
UPDATE jobs SET lat = 45.057534, lng = -93.073895 WHERE location = 'MN - Vadnais Heights' AND lat IS NULL;
UPDATE jobs SET lat = 40.213275, lng = -77.008041 WHERE location = 'PA - Mechanicsburg' AND lat IS NULL;
UPDATE jobs SET lat = 39.072279, lng = -76.546617 WHERE location = 'MD - Severna Park' AND lat IS NULL;
UPDATE jobs SET lat = 43.178853, lng = -88.117261 WHERE location = 'WI - Menomonee Falls,' AND lat IS NULL;
UPDATE jobs SET lat = 39.267508, lng = -76.798011 WHERE location = 'MD - Ellicott City' AND lat IS NULL;
UPDATE jobs SET lat = 36.978392, lng = -76.430752 WHERE location = 'VA - Newport News' AND lat IS NULL;
UPDATE jobs SET lat = 39.115461, lng = -77.564532 WHERE location = 'VA - Leesburg' AND lat IS NULL;
UPDATE jobs SET lat = 38.957161, lng = -77.358603 WHERE location = 'Reston, VA' AND lat IS NULL;
UPDATE jobs SET lat = 38.336326, lng = -77.051562 WHERE location = 'VA - Dahlgren' AND lat IS NULL;
UPDATE jobs SET lat = 39.534776, lng = -76.347558 WHERE location = 'MD - Bel Air' AND lat IS NULL;
UPDATE jobs SET lat = 38.916973, lng = -77.22899 WHERE location = 'VA - Tysons' AND lat IS NULL;
UPDATE jobs SET lat = 38.030395, lng = -78.477477 WHERE location = 'VA - Charlottesville' AND lat IS NULL;
UPDATE jobs SET lat = 38.974642, lng = -77.012197 WHERE location = 'MD - Takoma Park' AND lat IS NULL;
UPDATE jobs SET lat = 32.651728, lng = -96.908474 WHERE location = 'TX - Duncanville' AND lat IS NULL;
UPDATE jobs SET lat = 39.360585, lng = -77.323257 WHERE location = 'MD - Ijamsville' AND lat IS NULL;
UPDATE jobs SET lat = 37.523411, lng = -77.315845 WHERE location = 'VA - Sandston' AND lat IS NULL;
UPDATE jobs SET lat = 38.514595, lng = -89.981532 WHERE location = 'IL - Belliville' AND lat IS NULL;
UPDATE jobs SET lat = 38.812788, lng = -77.637698 WHERE location = 'VA - Haymarket' AND lat IS NULL;
UPDATE jobs SET lat = 38.81449, lng = -76.99862 WHERE location = 'MD - Forest Heights' AND lat IS NULL;
UPDATE jobs SET lat = 38.945797, lng = -77.155426 WHERE location = 'VA - Langley' AND lat IS NULL;
UPDATE jobs SET lat = 26.641868, lng = -81.871675 WHERE location = 'FL - Fort Myers' AND lat IS NULL;

-- Manually corrected — the automated geocode matched the wrong place
-- (verified via a state-bounding-box sanity check + retry with a
-- restricted `types=place` query where that fixed it):
UPDATE jobs SET lat = 38.87082, lng = -77.04982 WHERE location = 'VA - Pentagon' AND lat IS NULL;
UPDATE jobs SET lat = 41.343161, lng = -72.129927 WHERE location = 'CT - Waterford' AND lat IS NULL;
UPDATE jobs SET lat = 41.915159, lng = -71.91039 WHERE location = 'CT - Putnam' AND lat IS NULL;
-- Source data typo ("VA - ATlanta" — Atlanta is in GA, matches the two
-- sibling "GA - Atlanta"/"GA - ATlanta" entries already in the data):
UPDATE jobs SET lat = 33.750801, lng = -84.389855 WHERE location = 'VA - ATlanta' AND lat IS NULL;
-- Dulles isn't a standalone geocodable place — used Sterling, VA, the
-- town immediately adjacent to Washington Dulles International Airport:
UPDATE jobs SET lat = 39.001809, lng = -77.403409 WHERE location = 'VA - Dulles' AND lat IS NULL;
-- Source data typo ("Truth and Consequences" — the real town is
-- "Truth or Consequences, NM"):
UPDATE jobs SET lat = 33.128531, lng = -107.255683 WHERE location = 'NM - Truth and Consequences' AND lat IS NULL;
